CREATE TABLE STUDENTS (
  ID VARCHAR2(10) PRIMARY KEY,
  FIRST_NAME VARCHAR2(50) NOT NULL,
  LAST_NAME VARCHAR2(50) NOT NULL,
  COURSE VARCHAR2(50) NOT NULL,
  FEES NUMBER NOT NULL,
  EMAIL VARCHAR2(150),
  PHONE VARCHAR2(20)
);
